### ISSUE TITLE
Local themes override rotemplate

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-org/rotemplate#62]
Back before weathercan was part of rOpenSci, I had a red theme for the package docs. This was overridden by the rOpenSci theme, so I ignored it but never removed the red theme. Now in the new theme, parts of that original red show through (https://docs.ropensci.org/weathercan/). 

If this is just something I should fix on my end, I'll close the issue and deal with it :grin:,  but I thought I'd mention it in case it's undesirable behaviour from the template.

**Comment by maelle** [comment]
Thank you! We've been working on adding more locks as it's a regression indeed.

**Comment by jeroen** [comment]
Thanks for reporting. This was fixed in https://github.com/ropensci-org/rotemplate/pull/60 (we now ignore `extra.css` and `extra.js` when building the ropensci docs). Can you have a look at https://docs.ropensci.org/weathercan/ if everything looks OK now? (you may need to force-refresh in your browser to make sure you're seeing the latest version)

**Comment by steffilazerte** [comment]
Looks great!
